backend:
  name: github
  repo: Chloe-SD/jcard
  branch: main
  base_url: https://jcard.vercel.app/

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - name: "home"
        label: "Home Page"
        file: "content/home.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Subtitle", name: "subtitle", widget: "string" }
          - { label: "Hero Image", name: "heroImage", widget: "image" }
          - { label: "Body", name: "body", widget: "markdown" }
